kidd/org-gcal.el

- org-gcal.el
org-archive-subtree uses the usual kill functions to move subtrees around, leaving traces of the archived events in the `kill-ring` (normally not what you want).
This PR restores the old kill-ring after the archiving has happened.
> Avoid kill ring messup

- org-gcal.el
* alert.el already manages a default emacs logo. If user wants a
different one, set the new `org-gcal-logo-file' variable to the path
of the logo.
* removed `org-gcal-logo' variable
> Simplify notification logo setup

- org-gcal.el
Detect appropriate calendar id from current buffer when requesting
post or delete an event.  Raise user-error if no calendar id is found.
> Support multiple calendar.

- org-gcal.el
skip-import and skip-export are not used in delete-event-at-point
> remove unused variables

- org-gcal.el
This makes the code work with indirect buffers as well as normal buffers. 
Working with indirect buffers make org-gcal-post-at-point work with capture buffers, and make the capture hook work.
> Makes org-gcal work with indirect buffers

- org-gcal.el
Multi-line locations broke the org property drawer, leading to events not being identified correctly as already present (thus creating duplicates). In this PR I substituted newlines for ", " to remedy this issue.
>  Fix issue where multi-line locations led to duplicate calendar entries

- org-gcal.el
**Use of case**
As a calendar user, I often have hangout video-conferences bound to my calendar meetings. As follows:
So it is really useful for this use case to be able to join a meeting without having to open the calendar. Especially if you have several gmail accounts on the browser, since upon opening the calendar link, it opens always the default calendar. Meaning that in most cases the user has to manually switch calendars to click on the hangouts link.
This PR parses the hangouts link and shows it if present, as follows:
Then, by positioning the cursor on it and pressing C-c C-o it just opens on the browser. Simplifying this task a lot.
**Related discussions**
We have discussed about this in this issue #31.
> Add hangouts link if present.

- README.org
- org-gcal.el
- rmi-org-gcal.el
The goal of this PR is to allow moving entries containing events outside of the files in `org-gcal-file-alist` while retaining the ability to easily keep all the events in sync with the server.
First of all, the format of the entries containing events has been changed slightly. Two properties have been added:
- `:calendar-id:`: stores the calendar ID in order to avoid having to consult `org-gcal-file-alist`.
- `:ETag:`: stores the `ETag` field in Calendar API responses. This is used to determine later if the event has changed on the server since the last fetch (see below).
In addition:
- The `:ID:` entry has been changed to have the format `${EVENT_ID}/${CALENDAR_ID}` - i.e., event ID, slash, calendar ID. This is because events shared between calendars (for example, if I've invited my …
> Support events located outside of files in org-gcal-file-alist 

- org-gcal-test.el
- org-gcal.el
This prevents org-gcal-sync-buffer from considering the entry as a Calendar
event after deleting it.
Depends on #42
> org-gcal-delete-at-point: remove :org-gcal: drawer after deleting event

- README.org
In particular, describe event structure resulting from the enhancements in
https://github.com/kidd/org-gcal.el/pull/34. Also clarify some other
parts of the README.
Fixes #40
> Expand org-gcal README

- org-gcal.el
Remove two major performance issues for using Org IDs in bulk:
- `org-gcal--find-id-file` is like `org-id-find-id-file`, except that it
doesn't return the current buffer if the ID isn't found.
- `org-gcal--id-find` doesn't update `org-id-locations` if the ID isn't
found, avoiding a major source of GC pressure and overall increased work,
since we expect a lot of the time to search for IDs that don't yet
exist. Instead, we manually update `org-id-locations' as we add calendar
entries.
> Switch to private functions for finding Org IDs

- org-gcal.el
- Only use an existing ID if it matches the format of the IDs created by
org-gcal.
- Use `org-entry-get` and related functions instead of `org-element-property`
as much as feasible. `org-element-property` doesn't always read the first ID
in an entry, which is the behavior we want.
- Remove `org-gcal--property-from-name` because it's now unused.
- Only update org-id location when buffer file name not nil
> Fix some bugs in handling of ID properties:

- .travis.yml
- Cask
- org-gcal.el
This means that, after the first fetch of events, only events that have changed
will be retrieved by future calls to `org-gcal-sync` or `org-gcal-fetch`. To
save the sync tokens, org-gcal has taken a dependency on the
[`persist`](https://elpa.gnu.org/packages/persist.html) library.
With this sync, events on the first fetch will no longer necessarily be
retrieved in chronological order, because the `"orderBy"` parameter to the
Calendar API disables incremental sync. If this is important, you should
probably call `M-x org-sort` in your calendar event files yourself.
Fixes #77
> org-gcal-sync: enable incremental sync of events

- org-gcal.el
After adding incremental sync support, I overlooked that incremental syncs will
download *all* event changes in the future, rather than only those before
`org-gcal-down-days`. If a repeated event is modified and an incremental sync
is done, it will download repetitions of the event far into the future (I saw
events up to 2040 downloaded), which will probably add enough entries to your
Org file to slow it down quite a lot. In order to do this properly, we store an
expiration time after each full sync to remind us to do another full sync
`org-gcal-down-days` into the future.
Fixes #81
> Only fetch new events in range [org-gcal-up-days, org-gcal-down-days]

- org-gcal.el
Conform with examples on <https://developers.google.com/calendar/v3/>. As part
of this, remove the "key" and "grant_type" URL parameters from all URLs except
those to refresh and request tokens, which I think will fix some sporadic 400
HTTP status codes.
Also add "Accept" header everywhere. It's worked without it, but I'm adding it
to be consistent with the API documentation.
> Use Authorization header to pass access token rather than URL

- org-gcal.el
- test/org-gcal-test.el
- Prompt for Calendar ID if not present
- Prompt for event start time (current time by default)
- Prompt for duration (effort minus clocked time if present, or else 5 minutes)
Fix #85
> org-gcal-post-at-point: Default some properties

- README.org
- org-gcal.el
Before, we fetched individual instances of recurring events as single events, and didn't fetch the parent recurring events at all. However, it's nice to have the parent event present to keep in sync with an Org-mode habit. In addition, filing all the instances of recurring events under the parent event helps to keep gcal.org cleaner, making it much more usable.
Therefore, I've added an option `org-gcal-recurring-events-mode`. By default, the treatment of recurring events is the same as before - that is, they are inserted individually at the top level. However, if `org-gcal-recurring-events-mode` is set to `'nested`, we instead insert instances of recurring events under the parent event headline. See the updated README.org for more details.
> Fetch instances of recurring events

- org-gcal.el
This fixes #62, and most likely #68 and #99 as well. Namely, `org-gcal--capture-post` as a hook before org-capture finalization resulted in deferred errors and duplicate events (when used in conjunction with a `org-gcal-sync` hook). We change it to run after finalization which fixes these issues.
> Fix org-gcal--capture-post hook

- Makefile
- org-gcal-id.el
- org-gcal.el
- org-generic-id.el
- test/org-generic-id-test.el
Based on org-id, this library allows tracking any property as an ID. I
plan to use this for https://github.com/kidd/org-gcal.el/issues/100, to
switch org-gcal away from the ID property.
> Add org-generic-id library

- org-generic-id.el
- Add Autoloads to all public functions.
- Load `org-generic-id-locations` upon first load instead of having
each function do so.
> Fix loading of org-generic-id-locations

- org-generic-id.el
These imports were left over from `org-id`, but because `org-generic-id` has a reduced scope, it doesn't need these imports.
Fixes #130
> Remove unused imports from org-generic-id

- org-gcal.el
Follow-up to #106 discovered during implementing #134
> Fix error when running without `org-capture` loaded first

- Cask
- org-gcal.el
When the event ID was stored in the `ID` property, I decided to use
`ETag` as a backup to get greater assurance that the `ID` property that
might have already been stored in the event was known to GCal (and would
not 404). However, since commit 135cbe1
the event ID is stored in its own property, so the mere presence of an
`event-id` property means that the event is almost certainly known to
GCal.
This change makes the code more robust in case `ETag` is missing for
some reason, and makes generating headlines from `calendar-id` and
`event-id` which will then be populated by `org-gcal-post-at-point`
easier - it's no longer necessary to remember to add an `ETag` property,
which would be immediately overwritten anyway.
> org-gcal-post-at-point: work even if ETag is absent

- org-gcal.el
Show the authentication URL in the prompt when requesting an auth code from the user to support SSH/etc sessions where browse-url won't open the browser.
> feat: Show auth url in prompt

- org-gcal.el
Fix #177.
Manually tested with another calendar that contains a hash sign (`en.usa#holiday@group.v.calendar.google.com`, the US Holidays calendar).
> Encoding Google calendar event and instance URLs

- README.org
- org-gcal.el
- test/org-gcal-test.el
The "link" property on events will be synced with the "source"
[property in Google Calendar](https://developers.google.com/calendar/api/v3/reference/events#source).
Also clarify in README that the minimum requirements for Org-gcal.el are
now Emacs 26 and Org 9.3.
> Support syncing the "link" Org property with Google Calendar

- org-gcal.el
When using org-gcal-post-at-point and choosing one of the calendars you
have set in org-gcal-fetch-file-alist, you can get a list where it's
recognize some of your own calendars. Something like:
```
...
snatolhcagoesntibqvwmkjsanto@group.calendar.google.com
...
```
To address this, change the `completing-read` to show the file
associated with each calendar ID in `org-gcal-fetch-file-alist`.
Fix #178
> Add calendar file associated with calendar ID to prompt

- org-gcal.el
- test/org-gcal-test.el
- Support bare URL (no org-link syntax, or URL without description)
- Support `ROAM_REFS` as an alternative to `link` for org-roam files,
but only when round tripping is possible.
> Fixes to links

- org-gcal.el
Don't update existing headlines to say "busy" when an event is cancelled. This is caused by the cancelled event missing a title.
> Fix cancel

- README.org
In an effort to save new users time and frustration, this patch updates the README file with a warning about the broken auth workflow.
> Update README with warning about broken auth workflow

- org-gcal.el
- org-generic-id.el
- test/org-generic-id-test.el
This makes `org-gcal-sync` much faster, since `org-generic-id-update-id-locations` is called many times during updates.
> org-generic-id-update-id-locations: don't scan unmodified files

- org-generic-id.el
`plist-get` and `plist-put` don't work properly otherwise.
> Intern strings for use as plist keys

- org-generic-id.el
In https://github.com/kidd/org-gcal.el/pull/203 I reversed the test.
> Fix org-generic-id--last-update-id-time-put

- org-generic-id.el
To quote the emacs source:
(defun switch-to-buffer (buffer-or-name &optional norecord force-same-window) 
"Display buffer BUFFER-OR-NAME in the selected window.
WARNING: This is NOT the way to work on another buffer temporarily within a Lisp program!  
Use `set-buffer' instead.  That avoids messing with the window-buffer correspondences.
> Issue 202: Replace switch-to-buffer with set-buffer

- Cask
- Makefile
- README.org
- oauth2-auto.el
- org-gcal-pkg.el
- org-gcal.el
- test/org-gcal-test.el
This allows switching from the deprecated OOB flow
<https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob>,
fixing <https://github.com/kidd/org-gcal.el/issues/191>.
As a side effect, oauth2-auto makes it straightforward to support
multiple accounts (see
<https://github.com/kidd/org-gcal.el/issues/199>), although this
PR doesn't by itself enable that.
@rhaps0dy
> Switch to oauth2-auto for Google Calendar OAuth2

- oauth2-auto.el
Fix https://github.com/kidd/org-gcal.el/issues/207.
> Use float-time to get current epoch in seconds

- .github/workflows/main.yml
See https://github.com/lhotari/action-upterm/pull/18. We should go back to the upstream branch once the upstream PR is merged.
> Test branch for wait-timeout-minutes

- org-gcal.el
Fix https://github.com/kidd/org-gcal.el/issues/218.
> Ensure CLOSED timestamp isn’t wiped out by org-gcal-sync

- .github/workflows/main.yml
- Makefile
- org-gcal.el
- test/org-gcal-test.el
- test/org-generic-id-test.el
- test/org-test.el
Test updates:
- actions/cache: v2 -> v4.2.3 since [v2 has been disabled](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down).
- actions/checkout: v2 -> v4.2.2
- Pin purcell/setup-emacs, lhotari/action-update to current master commit hashes.
- Pin cask to 0.9.0
- Add newer Emacs versions to test matrix in Github action
- Disable a test that currently fails under Cask
> Github actions update

- .github/workflows/main.yml
- Don't run duplicate workflows on PRs.
- Pin all action versions to commit hashes.
- Improve how the Cask binary as well as Cask-installed packages are cached.
- Cask now installs in ~/.emacs.d/.cask as well, so cache that
- Track cache correctly per unique tuple of matrix.
- Use fixed Cask version correctly in setup-cask rather than snapshot.
- Add Nix store path of Emacs to cache key to catch changing snapshot versions.
> GitHub workflows update
