kidd/org-gcal.el

README.org
=> Documentation for myuhe PRs

README.org, org-gcal.el
Added proper error message and readme documentation about it.
=> Clarified parse error a bit.

org-gcal.el
Ported https://github.com/myuhe/org-gcal.el/pull/122 to this fork.
=> Fixed regexp that led to double property drawers & agenda entries

org-gcal.el
In certain cases, the marker returned from `org-id-find` will end up not
pointing to the Org entry corresponding to the ID by the time `org-gcal-sync`
is updating the entry. This seems to particularly be an issue with entries not
at the top level. At that point, `org-gcal--update-entry` ends up pointing to
the top-level ancestor of the event that we intended to update, overwriting
that instead (and causing duplicate IDs to be generated).
This change is an attempt to fix that issue. As soon as the original marker
from `org-id-find` is generated, we move to the beginning of the headline in
which the marker is located and generate a new marker there.
Once I've run this for a few days, I'll remove the calls to `message`.
=> org-gcal-sync: fix accidentally updating top-level parents of calendar entries

.gitignore, Makefile, README.org, org-gcal-test.el, test-org-gcal.el
=> Initial implementation of regression tests

README.org
Incorporate the updates to the procedure to obtain OAuth tokens from https://github.com/kidd/org-gcal.el/issues/58#issuecomment-565716543, as well as updates on how to authorize the app. Also fix some of the formatting.
Fixes #58
=> Update installation instructions for OAuth workflow changes

README.org, org-gcal.el
=> Document org-gcal-request-token, make it interactive.

.travis.yml, emacs-travis.mk, test/org-gcal-test.el
- Rewrite .travis.yml to use EVM
- Use correct Travis Emacs builds
=> Fix Travis-CI configuration

org-gcal.el
=> Use nextPageToken in org-gcal-sync to fetch all events matching search

README.org, org-gcal.el, test/org-gcal-test.el
=> Add options to cancel and remove events deleted on the server

org-gcal.el, org-generic-id.el, test/org-gcal-test.el
=> Use entry-id instead of ID property to store event IDs

org-gcal.el
I believe #108 wasn't fully fixed before. One of the ways I noticed that events can be duplicated is when 2 syncs are run at once. Let's prevent that.
=> Prevent running more than one sync at once

org-generic-id.el
=> Replace rx with rx-to-string

.github/workflows/main.yml, README.org
=> Add Github Actions to test repo

org-gcal.el
=> Add param to org-gcal--notify to silence messages

README.org, org-gcal.el, test/org-gcal-test.el
Trying to fix #48 by adding org-gcal-local-timezone for fetching events.
=> Add org-gcal-local-timezone to respect timezone

org-gcal.el
This will also create events when refiling into a file in `org-gcal-fetch-file-alist`.
=> Fix org-gcal--capture-post

org-gcal.el, test/org-gcal-test.el
=> Enable entries to be managed either by Org or Google Calendar

org-gcal.el
=> Remove :tag in defgroup

.github/workflows/main.yml
- Add Emacs 28.1 for testing
- Install Python 3.9
=> Update Github workflows
